### PR TITLE
match RemakeBGM

### PR DESCRIPTION
**Pull request by FatesTimelines1337**

### CODE REVIEW

**Comment by drojf** [comment]
wow, I'm surprised you were able to run it this yourself, I didn't think I wrote the instructions well enough that you could run the tool without problems.

Did you need to manually edit anything? or is this just the raw output of running the script?

**Comment by drojf** [comment]
Also if you just manually matched them instead of running the script, that's fine too, I just wasn't sure what you did

**Comment by FatesTimelines1337** [comment]
I converted the RemakeBGM files into opus files and ran the script to match them.

**Comment by drojf** [comment]
~~Can you send me the opus files so I can update the database?~~

**Comment by drojf** [comment]
oh wait, never mind, I thought you added opus files to the database, but they were already in the database

**Pull request merged**
